name: NotifySystem
version: ${notify.version}
main: eu.cloudnetservice.notify.plugin.ProjectMain

author: CloudNetService
website: https://cloudnetservice.eu/
description: CloudNet Notify System

depend: [CloudNetAPI]

